/* Curadoria editorial: apoio/comidas-pequim/. Fotos reais, verificadas visualmente. */
window.COMIDAS_PEQUIM = (() => {
  const fonte = (title, url) => ({title, url});
  const fontes = {
    lista2026: fonte('Governo de Pequim — Beijing Must-Try List (2026)', 'https://english.beijing.gov.cn/beijinginfo/videos/202606/t20260608_4691225.html'),
    niujie2026: fonte('Turismo de Pequim / Secretaria de Comércio — sabores de Niujie (2026)', 'https://www.visitbeijing.com.cn/article/4RSwGvEnoL0'),
    frios: fonte('Governo de Pequim — Thirteen Traditional Cold Foods', 'https://english.beijing.gov.cn/beijinginfo/culture/beijingfolklore/traditionalfood/202110/t20211018_2514810.html'),
    ruas: fonte('Turismo de Pequim — Culinary streets in Beijing', 'https://english.visitbeijing.com.cn/article/4EKustMwgbr'),
    pato: fonte('Governo de Pequim — gastronomia e patrimônio (2026)', 'https://english.beijing.gov.cn/latest/news/202602/t20260212_4511467.html'),
    grelha: fonte('Turismo de Pequim — Beijing Cuisine: Kao Rou Ji', 'https://english.visitbeijing.com.cn/article/47OOh80EpDm'),
    sabores: fonte('Turismo de Pequim — Experiencing old Beijing culture through taste', 'https://english.visitbeijing.com.cn/article/4Ij8fs8gdkc'),
    rua: fonte('Turismo de Pequim — Beijing’s Best Street Food', 'https://english.visitbeijing.com.cn/article/47ONa5PZNsz'),
    jiaozi: fonte('Turismo de Pequim — Wangfujing Snack Street: descrição dos pratos', 'https://english.visitbeijing.com.cn/article/47ONvf7EbSC'),
    dalian: fonte('Turismo de Pequim — Beijing Snack: Dalian Huoshao', 'https://english.visitbeijing.com.cn/article/47OO25ZVe1z'),
    porco: fonte('Turismo de Pequim — Beijing Style Shredded Pork', 'https://english.visitbeijing.com.cn/article/47ONoB9JKvG'),
    lanlong: fonte('Turismo de Pequim — Economical Snacks in Beijing', 'https://english.visitbeijing.com.cn/article/47ONv25oeWh'),
    miancha: fonte('Turismo de Pequim — Drawing a Map for Old Beijing Snacks', 'https://english.visitbeijing.com.cn/article/47ONnYsaNgj'),
    aiwowo: fonte('Turismo de Pequim — Qingming: snacks de Pequim', 'https://english.visitbeijing.com.cn/article/47OLTAlU6MD'),
    ameixa: fonte('Turismo de Pequim — Suan Mei Tang', 'https://english.visitbeijing.com.cn/article/47OO6NsndoP'),
    pera: fonte('Turismo de Pequim — Xiaodiao Pear Soup', 'https://english.visitbeijing.com.cn/article/47OOJXNDymE'),
  };
  const lojas = {
    quanjude: ['Quanjude — Qianmen', 'https://m.dianping.com/shop/508130/dishlist'],
    laoma: ['Laoma Shaomai — Andingmen', 'https://m.dianping.com/shop/4546950/dishlist'],
    baikui: ['Bai Kui — Andingmen', 'https://m.dianping.com/shop/H6dirMqzVWh8AyHA/dishlist'],
    fangzhuanchang: ['Fangzhuanchang 69 — Yonghegong', 'https://m.dianping.com/shop/H56vxEMxnsblnW2w/dishlist'],
    donglaishun: ['Donglaishun — Dashilar', 'https://m.dianping.com/shop/3546289/dishlist'],
    kaorouji: ['Kaorou Ji — Shichahai', 'https://m.dianping.com/shop/k81D6Qv7OPwwSWdH/dish75910'],
    xianlaoman: ['Xianlaoman — Andingmen', 'https://m.dianping.com/shop/509358/dishlist'],
    qingfeng: ['Qingfeng Baozi — Portão Leste do Palácio de Verão', 'https://m.dianping.com/shop/1438738836/dishlist'],
    zhougong: ['Zhougong Zhoupo — Qinglongqiao', 'https://m.dianping.com/shop/3194509/dishlist'],
    dalanlong: ['Da Lan Long — Yutingqiao', 'https://m.dianping.com/shop/77441089/dishlist'],
    ziguangyuan: ['Ziguangyuan — Dashilar', 'https://m.dianping.com/shop/H2DwdQFNHfVRq0Tm/dishlist'],
    duyichu: ['Duyichu — Qianmen', 'https://m.dianping.com/shop/2677600/dishlist'],
    xinhe: ['Xinhe Xiaoguan — Beixinqiao', 'https://m.dianping.com/shop/l9s0SPdv66hIawGd/dishlist'],
    xiaodiao: ['Xiao Diao Li Tang — Wangfujing / in88', 'https://m.dianping.com/shop/127544931/dishlist'],
    yangcheng: ['Yangcheng — Qianmen', 'https://m.dianping.com/shop/1667076465/dishlist'],
  };
  const foto = (id, alt, loja, extension = 'webp') => ({
    src: `fotos/${id}.${extension}`, alt,
    sourceUrl: lojas[loja][1],
    caption: `Foto representativa em ${lojas[loja][0]}; não necessariamente do local sugerido.`,
  });
  const catalogo = loja => fonte(`Dianping — prato observado em ${lojas[loja][0]} (set. 2026)`, lojas[loja][1]);
  return {
    updatedAt: '2026-09-21',
    items: [
      {
        id: 'pato-pequim', name: 'Pato de Pequim', nameZh: '北京烤鸭', pinyin: 'Běijīng kǎoyā', category: 'comida', regionalOrigin: 'Clássico de Pequim',
        description: 'Pato assado de pele crocante, servido em fatias; monte pequenas panquecas com a carne, pepino, cebolinha e molho.',
        whereToTry: 'Bianyifang (Xianyukou ou Yutingqiao), Quanjude (Qianmen) ou Siji Minfu nas regiões já selecionadas.',
        notes: 'Pedir molho separado e conferir ossos. Pato inteiro é para compartilhar; acompanhamentos podem ser cobrados à parte.',
        photos: [foto('pato-pequim', 'Pato assado fatiado com pele dourada, no Quanjude de Qianmen', 'quanjude')], sources: [fontes.pato, catalogo('quanjude')],
      },
      {
        id: 'chuanr', name: 'Churrasco chinês no espeto', nameZh: '羊肉串 / 烤串', pinyin: 'Yángròuchuàn / kǎochuàn', category: 'comida', regionalOrigin: 'Popular em Pequim; forte tradição do noroeste chinês',
        description: 'Espetinhos grelhados, especialmente de cordeiro, com cominho. Também há versões de bovino e frango.',
        whereToTry: 'Niujie: área de comidas do supermercado halal, nº 5. Laoma Shaomai e casas de churrasco das regiões selecionadas também oferecem espetos.',
        notes: 'Pedir 不放辣椒 (sem pimenta). Cominho não é pimenta, mas o tempero pode misturar os dois. Retirar o espeto antes de servir às crianças.',
        photos: [foto('chuanr', 'Espetos grelhados de cordeiro temperados, no Laoma Shaomai', 'laoma')], sources: [fontes.niujie2026, fontes.rua, catalogo('laoma')],
      },
      {
        id: 'mending-roubing', name: 'Bolinhos de carne para provar em Niujie', nameZh: '门钉肉饼', pinyin: 'Méndīng ròubǐng', category: 'comida', regionalOrigin: 'Pequim; tradição Hui',
        description: 'Bolinho alto e redondo, dourado na chapa, com carne e cebolinha. O nome lembra os cravos das portas antigas.',
        whereToTry: 'Qiaotou Huixiangyuan (桥头回香苑), Baizhifang Nanjie 34: nos arredores de Niujie, não na própria rua. Alternativa no roteiro: Bai Kui em Andingmen.',
        notes: 'Confirmar recheio bovino. O caldo interno sai muito quente. Não confundir 门钉肉饼 com 牛肉饼: “torta de bovino” também pode ser uma torta baixa e achatada.',
        photos: [foto('mending-roubing', 'Bolinhos altos e redondos 门钉肉饼, dourados na chapa, no Bai Kui', 'baikui')], sources: [fontes.niujie2026, fontes.ruas, catalogo('baikui')],
      },
      {
        id: 'zhajiangmian', name: 'Macarrão com molho de soja e carne', nameZh: '炸酱面', pinyin: 'Zhájiàngmiàn', category: 'comida', regionalOrigin: 'Versão clássica de Pequim',
        description: 'Macarrão de trigo com molho espesso de pasta de soja e carne, acompanhado de pepino e outros vegetais para misturar.',
        whereToTry: 'Fangzhuanchang 69: opções já cadastradas em Yonghegong, Nanluoguxiang, Qianmen e Palácio de Verão.',
        notes: 'Misturar pouco molho de cada vez: costuma ser salgado. Confirmar se a carne é porco ou bovino; pedir pimenta à parte.',
        photos: [foto('zhajiangmian', 'Bandeja de acompanhamentos e molho para zhajiangmian, no Fangzhuanchang 69', 'fangzhuanchang')], sources: [fontes.sabores, catalogo('fangzhuanchang')],
      },
      {
        id: 'hotpot-cobre', name: 'Hotpot pequinês na panela de cobre', nameZh: '铜锅涮肉 / 涮羊肉', pinyin: 'Tóngguō shuànròu / shuànyángròu', category: 'comida', regionalOrigin: 'Pequim; tradição de carneiro no caldo',
        description: 'Fatias finas de carneiro ou bovino cozidas à mesa numa panela com chaminé central, acompanhadas de molho de gergelim.',
        whereToTry: 'Donglaishun (Dashilar), Nanmen (Houhai), Ya’er Liji (Shichahai) ou Dehua Jubao (Xiyuan).',
        notes: 'Escolher 清汤 (caldo claro), conferir ingredientes e cozinhar bem as carnes. Molho e pimenta separados. Panela e vapor exigem atenção com as crianças.',
        photos: [foto('hotpot-cobre', 'Panela tradicional de cobre com chaminé central, no Donglaishun', 'donglaishun')], sources: [fontes.lista2026, catalogo('donglaishun')],
      },
      {
        id: 'zhizi-kaorou', name: 'Churrasco pequinês na chapa', nameZh: '炙子烤肉', pinyin: 'Zhìzi kǎoròu', category: 'comida', regionalOrigin: 'Churrasco tradicional de Pequim',
        description: 'Carne marinada em fatias, grelhada sobre chapa de ferro. É outra experiência além dos espetinhos; cordeiro é a especialidade do Kaorou Ji.',
        whereToTry: 'Kaorou Ji, junto a Shichahai / ponte Yinding, ou Kaorou Liu na seleção de Nanluoguxiang.',
        notes: 'Confirmar pimenta e coentro. Pedir carne pronta se não quiser cozinhar na mesa; pratos e chapa chegam muito quentes.',
        photos: [foto('zhizi-kaorou', 'Carneiro preparado pelo Kaorou Ji em Shichahai', 'kaorouji', 'jpg')], sources: [fontes.grelha, catalogo('kaorouji')],
      },
      {
        id: 'jianbing', name: 'Crepe chinês de café da manhã', nameZh: '煎饼 / 煎饼果子', pinyin: 'Jiānbǐng / jiānbǐng guǒzi', category: 'comida', regionalOrigin: 'Norte da China; muito comum em Pequim',
        description: 'Crepe de chapa com ovo, molho, cebolinha e uma massa crocante dentro. Recheios e espessura variam entre os estilos.',
        whereToTry: 'Barracas de café da manhã dos hutongs; também observado no Laoma Shaomai e no Bai Kui, em Andingmen.',
        notes: 'Pedir sem pasta de pimenta. Conferir ovo, gergelim e recheios; uma unidade costuma ser fácil de compartilhar.',
        photos: [foto('jianbing', 'Jianbing cortado, mostrando camadas de ovo, vegetais e massa crocante', 'laoma')], sources: [fontes.rua, catalogo('laoma')],
      },
      {
        id: 'jiaozi', name: 'Dumplings de carne', nameZh: '饺子', pinyin: 'Jiǎozi', category: 'comida', regionalOrigin: 'Norte da China; não exclusivo de Pequim',
        description: 'Massinhas recheadas, cozidas ou grelhadas. Uma oportunidade de comparar porco com vegetais e bovino com cebolinha.',
        whereToTry: 'Xianlaoman em Andingmen ou Gulou; lojas de dumplings nas regiões selecionadas.',
        notes: 'Escolher recheio nominal de porco ou bovino. 三鲜 (“três delícias”) pode conter camarão; não presumir que seja só carne. Molhos à parte.',
        photos: [foto('jiaozi', 'Dumplings de porco com folhas de funcho, no Xianlaoman', 'xianlaoman')], sources: [fontes.jiaozi, catalogo('xianlaoman')],
      },
      {
        id: 'baozi', name: 'Pãozinho de carne no vapor', nameZh: '包子', pinyin: 'Bāozi', category: 'comida', regionalOrigin: 'Chinês geral; cotidiano em Pequim',
        description: 'Pão macio e fofo, recheado de carne ou vegetais. O de bovino aparece entre os lanches tradicionais de Niujie.',
        whereToTry: 'Hongji em Niujie; Bai Kui em Andingmen; Qingfeng nas áreas do Palácio de Verão.',
        notes: 'Confirmar carne e tempero. Abrir antes para esfriar: recheio e caldo podem estar bem mais quentes que a massa.',
        photos: [foto('baozi', 'Baozi aberto com recheio de bovino, no Bai Kui', 'baikui')], sources: [fontes.niujie2026, catalogo('baikui')],
      },
      {
        id: 'dalian-huoshao', name: 'Pastel alongado grelhado', nameZh: '褡裢火烧', pinyin: 'Dālián huǒshāo', category: 'comida', regionalOrigin: 'Lanche tradicional de Pequim',
        description: 'Pacotinho alongado de massa fina recheada, dourado na frigideira: exterior crocante e interior suculento.',
        whereToTry: 'Qingfeng Baozi do Portão Leste do Palácio de Verão, onde o prato foi observado; procurar também pelo nome chinês em casas de lanches pequineses.',
        notes: 'Confirmar o recheio: existem misturas de carne e frutos do mar. Não interpretar o formato como garantia de recheio apenas de porco.',
        photos: [foto('dalian-huoshao', 'Pastéis alongados dalian huoshao dourados na frigideira', 'qingfeng')], sources: [fontes.dalian, catalogo('qingfeng')],
      },
      {
        id: 'shaobing', name: 'Pão de gergelim em camadas', nameZh: '麻酱烧饼', pinyin: 'Májiàng shāobǐng', category: 'comida', regionalOrigin: 'Norte da China; clássico acompanhamento em Pequim',
        description: 'Pão assado com pasta de gergelim e casquinha tostada. Combina com hotpot e com uma refeição simples de café da manhã.',
        whereToTry: 'Zhougong Zhoupo em Qinglongqiao ou casas de hotpot tradicional, conferindo a versão salgada no menu.',
        notes: 'Contém trigo e gergelim; há versões doces e salgadas. Não é a mesma coisa que tanghuoshao.',
        photos: [foto('shaobing', 'Pães salgados com gergelim e pasta de gergelim, no Zhougong Zhoupo', 'zhougong')], sources: [fontes.frios, catalogo('zhougong')],
      },
      {
        id: 'jingjiang-rousi', name: 'Porco em tiras com molho pequinês', nameZh: '京酱肉丝', pinyin: 'Jīngjiàng ròusī', category: 'comida', regionalOrigin: 'Culinária de Pequim',
        description: 'Tiras de porco em molho adocicado de pasta de soja, para enrolar em folhas finas de tofu com vegetais.',
        whereToTry: 'Xianlaoman em Andingmen; também aparece em várias casas de comida pequinesa das listas regionais.',
        notes: 'Em geral não depende de pimenta, mas confirmar o preparo. Pedir cebolinha crua separada se as crianças não gostarem.',
        photos: [foto('jingjiang-rousi', 'Tiras de porco com molho escuro e folhas de tofu, no Xianlaoman', 'xianlaoman')], sources: [fontes.porco, catalogo('xianlaoman')],
      },
      {
        id: 'lanlong', name: 'Rolo de pão no vapor com carne', nameZh: '懒龙', pinyin: 'Lǎnlóng', category: 'comida', regionalOrigin: 'Comida caseira do norte; familiar em Pequim',
        description: 'Rolo de massa de pão com carne, cozido no vapor e cortado em fatias. As camadas formam uma espiral.',
        whereToTry: 'Da Lan Long — Yutingqiao, entre as opções perto do hotel; também observado no Jinfang de Xianyukou.',
        notes: 'Há recheios de porco e de bovino; escolher explicitamente. Confirmar pimenta e deixar o centro esfriar.',
        photos: [foto('lanlong', 'Fatia de lanlong de porco com massa branca e recheio em espiral', 'dalanlong')], sources: [fontes.lanlong, catalogo('dalanlong')],
      },
      {
        id: 'niurou-mian', name: 'Macarrão no caldo de bovino', nameZh: '清汤牛肉面 / 牛肉拉面', pinyin: 'Qīngtāng niúròumiàn / niúròu lāmiàn', category: 'comida', regionalOrigin: 'Noroeste da China; comum nas casas Hui de Pequim',
        description: 'Macarrão em caldo de bovino; nas casas de lamian, a massa pode ser esticada à mão. Não é originário de Pequim.',
        whereToTry: 'Silk Road Yilan (丝路伊兰) em Niujie; alternativa já observada no roteiro: Bai Kui — Andingmen.',
        notes: 'Pedir 清汤 e 不放辣椒. “Caldo claro” não garante que o restaurante não acrescente óleo de pimenta por cima.',
        photos: [foto('niurou-mian', 'Macarrão da seção 清汤牛肉面 do Bai Kui; caldo e vegetais visíveis', 'baikui')], sources: [fontes.niujie2026, catalogo('baikui')],
      },
      {
        id: 'miancha', name: 'Mingau salgado com gergelim', nameZh: '面茶', pinyin: 'Miànchá', category: 'comida', regionalOrigin: 'Café da manhã tradicional de Pequim',
        description: 'Mingau espesso de painço com pasta de gergelim. Apesar de 茶 no nome, não é uma xícara de chá.',
        whereToTry: 'Bai Kui em Andingmen ou Huguosi Xiaochi em Di’anmen, ambos no roteiro.',
        notes: 'Sabor marcante de gergelim; confirmar se a pasta leva também amendoim. Servido quente; começar com uma tigela para compartilhar.',
        photos: [foto('miancha', 'Miancha com cobertura de pasta e sementes de gergelim', 'baikui')], sources: [fontes.miancha, catalogo('baikui')],
      },
      {
        id: 'lvdagun', name: 'Rolinhos de arroz com feijão doce', nameZh: '驴打滚', pinyin: 'Lǘdǎgǔn', category: 'doce', regionalOrigin: 'Doce tradicional de Pequim',
        description: 'Massa de arroz glutinoso enrolada com pasta doce de feijão e coberta por farinha de soja tostada.',
        whereToTry: 'Bancas de doces de Niujie, Huguosi em Di’anmen ou Donglaishun em Dashilar.',
        notes: 'Muito pegajoso; não oferecer o rolo inteiro às crianças pequenas. Contém soja e pode compartilhar utensílios com gergelim e castanhas.',
        photos: [foto('lvdagun', 'Rolinhos lvdagun com recheio escuro de feijão e pó claro de soja', 'donglaishun')], sources: [fontes.frios, fontes.niujie2026, catalogo('donglaishun')],
      },
      {
        id: 'wandouhuang', name: 'Doce delicado de ervilha amarela', nameZh: '豌豆黄', pinyin: 'Wāndòuhuáng', category: 'doce', regionalOrigin: 'Doce tradicional de Pequim',
        description: 'Doce firme e liso de ervilha amarela, servido em quadradinhos. Sabor suave e textura que desmancha.',
        whereToTry: 'Bai Kui em Andingmen ou Huguosi em Di’anmen; frequente em pratos de pequenos doces locais.',
        notes: 'É um doce de leguminosa, não um pudim de milho. Conferir ingredientes da versão da loja.',
        photos: [foto('wandouhuang', 'Quadrados amarelos de wandouhuang', 'baikui')], sources: [fontes.frios, catalogo('baikui')],
      },
      {
        id: 'aiwowo', name: 'Bolinho branco de arroz doce', nameZh: '艾窝窝', pinyin: 'Àiwōwo', category: 'doce', regionalOrigin: 'Doce tradicional de Pequim',
        description: 'Bolinho macio de arroz glutinoso com recheio doce; gergelim, sementes e frutas secas são combinações possíveis.',
        whereToTry: 'Bai Kui em Andingmen ou Huguosi Xiaochi em Di’anmen.',
        notes: 'Pegajoso e com recheio variável. Confirmar castanhas, sementes e tamanho dos pedaços antes de dividir com as crianças.',
        photos: [foto('aiwowo', 'Aiwowo aberto, mostrando arroz branco e recheio doce com frutas e sementes', 'baikui')], sources: [fontes.aiwowo, catalogo('baikui')],
      },
      {
        id: 'tanghulu', name: 'Espetinho de fruta caramelizada', nameZh: '冰糖葫芦', pinyin: 'Bīngtánghúlu', category: 'doce', regionalOrigin: 'Norte da China; ícone das ruas de Pequim',
        description: 'Fruta com uma casquinha de açúcar crocante. A versão clássica leva shanzha, uma frutinha ácida de espinheiro chinês.',
        whereToTry: 'Bancas de doces em Nanluoguxiang, Shichahai e ruas comerciais; procurar o nome 冰糖葫芦 e conferir a fruta.',
        notes: 'Atenção ao palito, caroços e casca dura de açúcar. Não dar as bolinhas inteiras para as crianças pequenas.',
        photos: [foto('tanghulu', 'Tanghulu de shanzha vermelho em espetinhos', 'baikui')], sources: [fontes.lista2026, fontes.rua, catalogo('baikui')],
      },
      {
        id: 'suannai', name: 'Iogurte pequinês', nameZh: '酸奶 / 奶皮子酸奶', pinyin: 'Suānnǎi / nǎipízi suānnǎi', category: 'doce', regionalOrigin: 'Tradição láctea local; várias apresentações atuais',
        description: 'Iogurte doce e levemente ácido. Pode vir em potinho ou jarra; uma versão popular atual traz uma camada de nata.',
        whereToTry: 'Ziguangyuan — Dashilar, onde foi observada a versão com nata; outras casas locais vendem iogurte próprio.',
        notes: 'Contém leite; versões industrializadas e artesanais não são idênticas. A foto é da versão com nata, não da jarra clássica.',
        photos: [foto('suannai', 'Potes de iogurte com nata 奶皮子酸奶 do Ziguangyuan', 'ziguangyuan')], sources: [fontes.rua, catalogo('ziguangyuan')],
      },
      {
        id: 'tanghuoshao', name: 'Pão doce de gergelim e açúcar escuro', nameZh: '糖火烧', pinyin: 'Tánghuǒshāo', category: 'doce', regionalOrigin: 'Tradicional em Pequim; raízes em Hebei',
        description: 'Bolinho assado denso, de cor escura, com açúcar mascavo e pasta de gergelim entre as camadas.',
        whereToTry: 'Bai Kui em Andingmen; procurar também nas bancas tradicionais de doces de Niujie.',
        notes: 'Contém trigo e gergelim; é doce e mais pesado que um pão simples. Bom para provar em pedaços.',
        photos: [foto('tanghuoshao', 'Tanghuoshao aberto mostrando a massa escura e as camadas', 'baikui')], sources: [fontes.frios, fontes.miancha, catalogo('baikui')],
      },
      {
        id: 'naiyou-zhagao', name: 'Bolinho frito doce de leite', nameZh: '奶油炸糕', pinyin: 'Nǎiyóu zhágāo', category: 'doce', regionalOrigin: 'Lanche tradicional de Pequim',
        description: 'Bolinho doce frito, dourado e leve por dentro, servido com açúcar. Não é necessariamente recheado como um sonho brasileiro.',
        whereToTry: 'Nailao Wei na região de Niujie, citado no guia local de 2026; também observado no Bai Kui.',
        notes: 'Confirmar leite, ovo e farinha; receitas variam. Melhor recém-feito, depois de esfriar o suficiente.',
        photos: [foto('naiyou-zhagao', 'Bolinhos fritos naiyou zhagao cobertos com açúcar', 'baikui')], sources: [fontes.niujie2026, fontes.frios, catalogo('baikui')],
      },
      {
        id: 'sachima', name: 'Quadradinho de massa frita com calda', nameZh: '沙琪玛 / 萨其马', pinyin: 'Shāqímǎ / sàqímǎ', category: 'doce', regionalOrigin: 'Origem manchu; tradicional em Pequim',
        description: 'Tirinhas de massa frita unidas por uma calda doce, cortadas em blocos. A textura pode ser macia ou mais crocante.',
        whereToTry: 'Ziguangyuan — Dashilar; lojas tradicionais de confeitaria, procurando o nome chinês na etiqueta.',
        notes: 'Pode conter ovo, trigo, gergelim e frutas secas. Conferir ingredientes; não presumir que todo sachima seja igual.',
        photos: [foto('sachima', 'Bloco de sachima com tiras de massa dourada e sementes de gergelim', 'ziguangyuan')], sources: [fontes.frios, catalogo('ziguangyuan')],
      },
      {
        id: 'gongting-nailao', name: 'Doce cremoso de leite imperial', nameZh: '宫廷奶酪', pinyin: 'Gōngtíng nǎilào', category: 'doce', regionalOrigin: 'Sobremesa tradicional de Pequim',
        description: 'Sobremesa suave de leite, firme e cremosa, normalmente comida de colher. “Nailao” aqui não significa uma fatia de queijo ocidental.',
        whereToTry: 'Nailao Wei (奶酪魏), Guang’anmen Neidajie 202, sala 107, região de Niujie; Duyichu em Qianmen também tinha o prato no catálogo.',
        notes: 'Contém leite. Algumas receitas usam fermento ou vinho de arroz: confirmar o preparo e não presumir ausência de álcool.',
        photos: [foto('gongting-nailao', 'Pote de sobremesa láctea 宫廷奶酪 do Duyichu', 'duyichu')], sources: [fontes.niujie2026, catalogo('duyichu')],
      },
      {
        id: 'suanmeitang', name: 'Bebida agridoce de ameixa', nameZh: '酸梅汤', pinyin: 'Suānméitāng', category: 'bebida', regionalOrigin: 'Bebida tradicional de Pequim',
        description: 'Bebida de ameixa defumada, adocicada e ácida; pode levar flores de osmanthus. Apesar de 汤, costuma ser uma bebida, não uma sopa salgada.',
        whereToTry: 'Restaurantes das regiões selecionadas; a marca Xinyuanzhai (信远斋) também aparece em garrafas.',
        notes: 'Pode ser bastante doce e ter sabor defumado. Confirmar gelo, açúcar e ingredientes na versão escolhida.',
        photos: [foto('suanmeitang', 'Garrafa de suanmeitang Xinyuanzhai, observada no Xinhe Xiaoguan', 'xinhe')], sources: [fontes.ameixa, catalogo('xinhe')],
      },
      {
        id: 'beibingyang', name: 'Refrigerante Beibingyang', nameZh: '北冰洋汽水', pinyin: 'Běibīngyáng qìshuǐ', category: 'bebida', regionalOrigin: 'Marca associada a Pequim',
        description: 'O refrigerante do “Oceano Ártico”, reconhecível pelo urso no rótulo. A versão cítrica é uma combinação frequente com pratos locais.',
        whereToTry: 'Restaurantes populares e lojas de conveniência; observado em várias fichas do roteiro.',
        notes: 'Refrigerante açucarado e com gás. Conferir o sabor no rótulo; latas e garrafas podem variar.',
        photos: [foto('beibingyang', 'Garrafa do refrigerante cítrico Beibingyang', 'laoma')], sources: [fontes.lista2026, catalogo('laoma')],
      },
      {
        id: 'cha-jasmim', name: 'Chá de jasmim', nameZh: '茉莉花茶', pinyin: 'Mòlì huāchá', category: 'bebida', regionalOrigin: 'Cultura do chá de Pequim',
        description: 'Chá perfumado com flores de jasmim, normalmente servido sem leite. Boa pausa entre as refeições e os passeios.',
        whereToTry: 'Wuyutai na Qianmen, nº 42, ou Zhangyiyuan na área de Dashilar; também disponível em restaurantes tradicionais.',
        notes: 'Contém cafeína; escolher a bebida pensando nos adultos. Conferir se o preço é por pessoa, xícara ou bule.',
        photos: [foto('cha-jasmim', 'Bule e xícara de chá de jasmim servidos no Quanjude', 'quanjude')], sources: [fontes.pato, fontes.lista2026, catalogo('quanjude')],
      },
      {
        id: 'xiaodiao-litang', name: 'Bebida doce de pera cozida', nameZh: '小吊梨汤', pinyin: 'Xiǎodiào lítāng', category: 'bebida', regionalOrigin: 'Sabor associado aos hutongs de Pequim',
        description: 'Pera cozida lentamente numa bebida doce, por vezes com tremella. Pode ser servida em pequeno bule ou jarra.',
        whereToTry: 'Xiao Diao Li Tang — Wangfujing / Yintai in88, já presente na seleção de restaurantes.',
        notes: 'Confirmar açúcar, mel e demais ingredientes; não atribuímos efeitos medicinais. Deixar esfriar antes de oferecer às crianças.',
        photos: [foto('xiaodiao-litang', 'Xícara de bebida doce de pera do Xiao Diao Li Tang', 'xiaodiao')], sources: [fontes.pera, catalogo('xiaodiao')],
      },
      {
        id: 'douzhi', name: 'Douzhi: bebida fermentada local', nameZh: '豆汁儿', pinyin: 'Dòuzhīr', category: 'bebida', regionalOrigin: 'Especialidade de Pequim; sabor de adaptação',
        description: 'Bebida fermentada de feijão-mungo, de sabor ácido e aroma forte. Tradicionalmente acompanhada de anéis fritos jiaoquan e conservas.',
        whereToTry: 'Bai Kui em Andingmen, Huguosi em Di’anmen ou Yinsan em Dashilar.',
        notes: 'Experiência para os adultos curiosos: começar com pouca quantidade. Não confundir com 豆浆 (doujiang), a bebida comum de soja.',
        photos: [foto('douzhi', 'Tigela de douzhi com acompanhamentos ao fundo, no Bai Kui', 'baikui')], sources: [fontes.sabores, catalogo('baikui')],
      },
      {
        id: 'yanjing', name: 'Cerveja Yanjing', nameZh: '燕京啤酒', pinyin: 'Yānjīng píjiǔ', category: 'bebida', regionalOrigin: 'Cerveja de Pequim',
        description: 'Marca local de cerveja para comparar com as cervejas que vocês já conhecem. Existem diferentes versões; a foto mostra a U8.',
        whereToTry: 'Restaurantes e lojas de conveniência; observada em fichas de Qianmen, Andingmen e perto do Templo do Céu.',
        notes: 'Bebida alcoólica, somente para adultos. Conferir teor e tamanho da garrafa; não há bebida infantil equivalente implícita nesta opção.',
        photos: [foto('yanjing', 'Garrafa da cerveja Yanjing U8', 'yangcheng')], sources: [fontes.lista2026, catalogo('yangcheng')],
      },
    ],
  };
})();
